# -*- coding: utf-8 -*-
"""ann

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19LDliKaPekDTEmrFZKsNwtPG8qkZLWEi
"""

import pandas as pd
data=pd.read_csv("/content/heart.csv")
print(data.head())
print(f"Number of duplicate rows: {data.duplicated().sum()}")
print(data.isnull().mean()*100)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['thal']=label_encoder.fit_transform(data['thal'])
print(data.head())
x=data.drop(columns=["target"])
y=(data[['target']])
# print(x.head())
# print(y.head())

from sklearn.preprocessing import StandardScaler
x_scaler=StandardScaler()
x_scaled=x_scaler.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential ([
    Dense(13,  input_shape=(13,)),
    Dense(53, activation="sigmoid"),
    Dense(67, activation="sigmoid"),
    Dense(1, activation="sigmoid")
])
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(x_train, y_train, epochs=1000)

import joblib
joblib.dump(model, "model.pkl")
joblib.dump(x_scaler, 'x_scaler.pkl')
joblib.dump(label_encoder, "label_encoder.pkl")

import tensorflow as tf
model.save('model.h5')



