# -*- coding: utf-8 -*-
"""predict ann

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1klv3eSzKAa6KpT0MA58osEUWcAK18lV4
"""

from tensorflow.keras.models import load_model
model = load_model("/content/model.h5")

import joblib
x_scaler = joblib.load("/content/x_scaler (1).pkl")
label_encoder = joblib.load("/content/label_encoder.pkl")


age = int(input("Age: "))
sex = int(input("Sex (0=female, 1=male): "))
cp = int(input("Chest Pain Type: "))
trestbps = int(input("Resting Blood Pressure: "))
chol = int(input("Cholesterol: "))
fbs = int(input("Fasting Blood Sugar (0/1): "))
restecg = int(input("Resting ECG: "))
thalach = int(input("Max Heart Rate: "))
exang = int(input("Exercise Induced Angina (0/1): "))
oldpeak = float(input("Oldpeak: "))
slope = int(input("Slope: "))
ca = int(input("Number of Major Vessels (ca): "))
thal = input("Thal: ")
thal = label_encoder.transform([thal])[0]

import pandas as pd
new_data = pd.DataFrame([[age, sex, cp, trestbps, chol, fbs,restecg, thalach, exang, oldpeak,
                        slope, ca, thal]],
                        columns=['age','sex','cp','trestbps','chol','fbs',
                                 'restecg','thalach','exang','oldpeak',
                                 'slope','ca','thal'])


new_data_scaled = x_scaler.transform(new_data)
prediction = model.predict(new_data_scaled)

if prediction[0][0] > 0.5:
    print("Heart Disease Detected")
else:
    print("No Heart Disease")